import { Song } from "@/types";
import {
  harLamhaNayaLyricsData,
  kaleidoscopeHeartLyricsData,
  ruchiMyQueenLyricsData,
  sameOficeDifferentHeartLyricsData,
  kidsNightMusicalLyricsData,
  lipsaBirthdaySongLyricsData,
  nirvanBirthdaySongLyricsData,
  ramAkankshaWeddingAnthemLyricsData,
  unChainedLyricsData,
  birthdayBluePartyLyricsData,
  sweetDreamsTonightLyricsData,
  akashBirthdayBashLyricsData,
  yaaraLyricsData,
  jashnEHemaliLyricsData,
  jassiDiJaanLyricsData,
  aDreamNamedJivyLyricsData
} from "./lyrics-data";


export const customCreations: Song[] = [
  {
    id: 11,
    created_at: "2024-01-01T00:00:00Z",
    title: "Ruchi My Queen",
    lyrics: null,
    timestamp_lyrics: ruchiMyQueenLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Rap",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/ruchi-my-queen.mp3",
    duration: "179",
    slug: "ruchi-my-queen",
    categories: ["Hip Hop", "Rap", "Urban"],
  },
  {
    id: 1,
    created_at: "2024-01-01T00:00:00Z",
    title: "Kaleidoscope Heart",
    lyrics: null,
    timestamp_lyrics: kaleidoscopeHeartLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Romantic Song",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/kaleidoscope.mp3",
    duration: "189",
    slug: "kaleidoscope-heart",
    categories: ["Romantic", "Acoustic", "Ballad"],
  },
  {
    id: 2,
    created_at: "2024-01-01T00:00:00Z",
    title: "Same Office, Different Hearts",
    lyrics: null,
    timestamp_lyrics: sameOficeDifferentHeartLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Love Story",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/office-love.mp3",
    duration: "195",
    slug: "same-office-different-hearts",
  },
  {
    id: 3,
    created_at: "2024-01-01T00:00:00Z",
    title: "A kid's night musical",
    lyrics: null,
    timestamp_lyrics: kidsNightMusicalLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Musical",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/kids-musical.mp3",
    duration: "181",
    slug: "kids-night-musical",
  },
  {
    id: 4,
    created_at: "2024-01-01T00:00:00Z",
    title: "Lipsa Birthday Song",
    lyrics: null,
    timestamp_lyrics: lipsaBirthdaySongLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Birthday Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/birthday-queen.mp3",
    duration: "181",
    slug: "lipsa-birthday-song",
    categories: ["Birthday", "Celebration", "Party"],
  },
  {
    id: 5,
    created_at: "2024-01-01T00:00:00Z",
    title: "Nirvan's Birthday Song",
    lyrics: null,
    timestamp_lyrics: nirvanBirthdaySongLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Birthday Party",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/nirvan-birthday.mp3",
    duration: "113",
    slug: "nirvan-birthday-song",
  },
  {
    id: 6,
    created_at: "2024-01-01T00:00:00Z",
    title: "Ram and Akanksha's wedding anthem",
    lyrics: null,
    timestamp_lyrics: ramAkankshaWeddingAnthemLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Wedding Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/wedding-anthem.mp3",
    duration: "180",
    slug: "ram-akanksha-wedding-anthem",
    categories: ["Wedding", "Celebration", "Romantic"],
  },
  {
    id: 7,
    created_at: "2024-01-01T00:00:00Z",
    title: "Unchained",
    lyrics: null,
    timestamp_lyrics: unChainedLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Motivational Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/unchained.mp3",
    duration: "180",
    slug: "unchained",
  },
  {
    id: 8,
    created_at: "2024-01-01T00:00:00Z",
    title: "Birthday Boy's Blue Party",
    lyrics: null,
    timestamp_lyrics: birthdayBluePartyLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Kids Birthday Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/blue-party.mp3",
    duration: "150",
    slug: "birthday-blue-party",
  },
  {
    id: 9,
    created_at: "2024-01-01T00:00:00Z",
    title: "Sweet Dreams Tonight",
    lyrics: null,
    timestamp_lyrics: sweetDreamsTonightLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Lullaby",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/sweet-dreams-tonight.mp3",
    duration: "200",
    slug: "sweet-dreams-tonight",
    categories: ["Lullaby", "Sleep", "Calm"],
  },
  {
    id: 10,
    created_at: "2024-01-01T00:00:00Z",
    title: "Akash's Birthday Bash Song",
    lyrics: null,
    timestamp_lyrics: akashBirthdayBashLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Birthday Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/akash-birthday.mp3",
    duration: "181",
    slug: "akash-birthday-bash",
  },
  {
    id: 12,
    created_at: "2024-01-01T00:00:00Z",
    title: "Yaara",
    lyrics: null,
    timestamp_lyrics: yaaraLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Romantic Song",
    service_provider: "Melodia",
    song_requester: null,
    prompt: null,
    song_url: "/audio/yaara.mp3",
    duration: "197",
    slug: "yaara",
  },
  {
    id: 13,
    created_at: "2024-01-01T00:00:00Z",
    title: "Har Lamha Naya",
    lyrics: null,
    timestamp_lyrics: harLamhaNayaLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Love Song",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/har-lamha-naya.mp3",
    duration: "269",
    slug: "har-lamha-naya",
  },
  {
    id: 14,
    created_at: "2024-01-01T00:00:00Z",
    title: "Jashn-e-Hemali",
    lyrics: null,
    timestamp_lyrics: jashnEHemaliLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Birthday Party Song",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/jashn-e-hemali.mp3",
    duration: "174",
    slug: "jashn-e-hemali",
  },
  {
    id: 15,
    created_at: "2024-01-01T00:00:00Z",
    title: "Jassi-di-jaan",
    lyrics: null,
    timestamp_lyrics: jassiDiJaanLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Punjabi Romantic Song",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/jassi-di-jaan.mp3",
    duration: "174",
    slug: "jassi-di-jaan",
  },
  {
    id: 16,
    created_at: "2024-01-01T00:00:00Z",
    title: "A Dream Named Jivy",
    lyrics: null,
    timestamp_lyrics: aDreamNamedJivyLyricsData,
    timestamped_lyrics_variants: null,
    selected_variant: 0,
    timestamped_lyrics_api_responses: null,
    music_style: "Mother's Love Lullaby",
    song_requester: null,
    prompt: null,
    service_provider: "Melodia",
    song_url: "/audio/a-dream-named-jivy.mp3",
    duration: "274",
    slug: "a-dream-named-jivy",
  },
];

export const testimonials = [
  {
    id: 1,
    title: "Perfect Birthday Surprise!",
    content:
      "Melodia created the most beautiful birthday song for my daughter. She absolutely loved it and it made her day so special. The personalized lyrics brought smile to my face!",
    author: "Priya S.",
  },
  {
    id: 2,
    title: "Our Wedding Song Dreams",
    content:
      "We wanted something unique for our first dance and Melodia delivered beyond our expectations. The song perfectly captured our love story.",
    author: "Rohit & Kavya",
  },
  {
    id: 3,
    title: "Heartfelt Apology Song",
    content:
      "I messed up big time with my partner and needed something special to make amends. The apology song Melodia created helped me express what I couldn't say in words.",
    author: "Arjun M.",
  },
  {
    id: 4,
    title: "Thank You Mom",
    content:
      "Created a thank you song for my mother on Mother's Day. The way they captured all the little memories and moments was incredible. Mom still plays it every day!",
    author: "Sneha K.",
  },
  {
    id: 5,
    title: "Farewell to a Dear Friend",
    content:
      "When my best friend moved across the country, I wanted to give her something meaningful. The farewell song they created perfectly expressed our friendship and the memories we shared.",
    author: "Vikram T.",
  },
];