import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-900">
      <Header />
      <div className="py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-white mb-4">
            Terms and Conditions
          </h1>
          <p className="text-xl text-gray-300">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="bg-slate-800 rounded-lg shadow-lg p-8 prose prose-lg max-w-none border border-slate-700">
          <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-300 mb-6">
            By accessing and using Melodia (&quot;the Service&quot;), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
          <p className="text-gray-300 mb-6">
            Melodia is an AI-powered platform that creates personalized songs based on user input. Our service includes:
          </p>
          <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2">
            <li>AI-generated lyrics creation</li>
            <li>Music composition and arrangement</li>
            <li>Song generation and delivery</li>
            <li>User account management</li>
            <li>Song storage and playback</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts</h2>
          <p className="text-gray-300 mb-4">
            To use certain features of our service, you must create an account. You agree to:
          </p>
          <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2">
            <li>Provide accurate, current, and complete information</li>
            <li>Maintain and update your account information</li>
            <li>Keep your password secure and confidential</li>
            <li>Accept responsibility for all activities under your account</li>
            <li>Notify us immediately of any unauthorized use</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mb-4">4. Content and Intellectual Property</h2>
          <h3 className="text-xl font-semibold text-gray-800 mb-3">4.1 User Content</h3>
          <p className="text-gray-300 mb-4">
            You retain ownership of any content you provide to us, including song requests, personal information, and custom lyrics. By using our service, you grant us a license to use this content to provide our services.
          </p>

          <h3 className="text-xl font-semibold text-gray-800 mb-3">4.2 Generated Songs</h3>
          <p className="text-gray-300 mb-4">
            Songs generated by our AI are created based on your input and preferences. You have the right to use these songs for personal purposes. However, commercial use may be subject to additional terms and licensing requirements.
          </p>

          <h3 className="text-xl font-semibold text-gray-800 mb-3">4.3 Our Intellectual Property</h3>
          <p className="text-gray-300 mb-6">
            The Melodia platform, including its design, functionality, and underlying technology, is protected by intellectual property laws. You may not copy, modify, or distribute our platform without permission.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">5. Payment and Billing</h2>
          <p className="text-gray-300 mb-4">
            Our service may include paid features. By subscribing to paid services, you agree to:
          </p>
          <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2">
            <li>Pay all applicable fees as described on our pricing page</li>
            <li>Provide accurate billing information</li>
            <li>Authorize us to charge your payment method</li>
            <li>Understand that fees are non-refundable unless otherwise stated</li>
            <li>Accept that prices may change with notice</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mb-4">6. Prohibited Uses</h2>
          <p className="text-gray-300 mb-4">
            You may not use our service for:
          </p>
          <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2">
            <li>Creating content that is illegal, harmful, or violates any laws</li>
            <li>Generating songs with offensive, defamatory, or inappropriate content</li>
            <li>Attempting to reverse engineer or hack our platform</li>
            <li>Using automated systems to access our service</li>
            <li>Violating any intellectual property rights</li>
            <li>Creating content that promotes violence, discrimination, or hate speech</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mb-4">7. Privacy and Data Protection</h2>
          <p className="text-gray-300 mb-6">
            Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your information. By using our service, you consent to our data practices as described in our Privacy Policy.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">8. Service Availability</h2>
          <p className="text-gray-300 mb-6">
            We strive to provide continuous service availability, but we cannot guarantee uninterrupted access. We may temporarily suspend or modify our service for maintenance, updates, or other reasons. We are not liable for any downtime or service interruptions.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">9. Limitation of Liability</h2>
          <p className="text-gray-300 mb-6">
            To the maximum extent permitted by law, Melodia shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or use, arising from your use of our service.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">10. Termination</h2>
          <p className="text-gray-300 mb-4">
            We may terminate or suspend your account and access to our service at any time, with or without cause, with or without notice. Upon termination:
          </p>
          <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2">
            <li>Your right to use the service will cease immediately</li>
            <li>We may delete your account and associated data</li>
            <li>You remain responsible for any outstanding payments</li>
          </ul>

          <h2 className="text-2xl font-semibold text-white mb-4">11. Changes to Terms</h2>
          <p className="text-gray-300 mb-6">
            We reserve the right to modify these terms at any time. We will notify users of significant changes via email or through our platform. Your continued use of the service after changes constitutes acceptance of the new terms.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">12. Governing Law</h2>
          <p className="text-gray-300 mb-6">
            These terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions. Any disputes arising from these terms shall be resolved in the courts of California.
          </p>

          <h2 className="text-2xl font-semibold text-white mb-4">13. Contact Information</h2>
          <p className="text-gray-300 mb-6">
            If you have any questions about these Terms and Conditions, please contact us at:
          </p>
          <div className="bg-gray-50 p-4 rounded-lg">
            <p className="text-gray-300">
              <strong>Email:</strong> legal@melodia.com<br />
              <strong>Address:</strong> 123 Music Street, Creative District, San Francisco, CA 94102<br />
              <strong>Phone:</strong> +1 (555) 123-4567
            </p>
          </div>

          <div className="mt-8 p-4 bg-yellow-50 border-l-4 border-yellow-400">
            <p className="text-yellow-800">
              <strong>Note:</strong> This is a template Terms and Conditions page. Please consult with a legal professional to ensure compliance with applicable laws and regulations in your jurisdiction.
            </p>
          </div>
        </div>
      </div>
      </div>
      <Footer />
    </div>
  );
}
